import Head from 'next/head'
import AppNavbar from '../components/AppNavbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppNavbar/>
      <hr/>
      <h1>Home Page</h1>
    </div>
  )
}
